### ISSUE TITLE
 lcd_pcf8574A requires some addition yaml code

### ISSUE THREAD

**Issue by arrikhan** [frasskungin/esphome-phsensor#6]
On Installing a PCF8574**A** unit, the yaml in example wouldn't support the device out of the box.

When using one of these devices, the scan should detect the address. The default is 0x3f and isn't specified in the yaml. On checking logs it will identify the address for you. Add this line under 'display:" to correctly address unit (use address you find in logs).

`address: 0x27`

Once past this issue, you will run into a frequency issue from the device. In my searching i found adding a frequency setting under 'i2c' resolved the following message, "Component lcd_base took a long time for an operation".

`frequency: 800kHz`

Complete code snippet with updates shown below.

```
i2c:
  sda: D2
  scl: D1
  frequency: 800kHz
  scan: true
  
display:
  - platform: lcd_pcf8574
    address: 0x27
    dimensions: 16x2
```
